inputKeyword 와 answerKeyword 를 비교하는 기능 추가
giibeom/java-wordle pull request #4
Opened 2023-03-27 14:31 UTC by seung-00

## 작업 요약
- inputKeyword 와 answerKeyword 를 비교하는 기능을 추가합니다

## 작업 내용

- [x]  inputKeyword 와 answerKeyword 를 비교하는 기능을 추가합니다
- [x]  inputKeyword 와 answerKeyword 를 비교하는 기능의 테스트 코드를 추가합니다

<br>

## 참고 자료

2023-03-27 14:42 UTC, seung-00 reviewed
저도 바로 코멘트를 남깁니다. 역시 네이밍이 제일 어렵네요 😅

2023-03-27 14:42 UTC, seung-00 commented on src/main/java/woowaapplication/pair/game/wordle/WordleGame.java
> +        return result;
a: result 보다 resultBlocks 가 더 명시적일 것 같네요~

2023-03-27 14:42 UTC, seung-00 commented on src/main/java/woowaapplication/pair/game/wordle/WordleGame.java
>          WordleBlock[] result = new WordleBlock[5];
a: 여기도 마찬가지로 resultBlocks 로 바꿔도 좋을 것 같네요

2023-03-27 14:42 UTC, seung-00 commented on src/main/java/woowaapplication/pair/game/wordle/WordleGame.java
> +    private WordleBlock compareLetters(char inputKeywordLetter, char answerKeywordLetter, Set<Character> inputKeywordLetters) {
a: 짜놓고 보니 inputLetter, answerLetter 만으로도 기존과 의미 전달이 비슷한 수준으로 되지 않을까? 라는 생각이 들었습니다. 
입력 글자, 정답 글자...

2023-03-27 15:00 UTC, giibeom requested changes
RCA 룰을 적용하여 리뷰를 진행하였습니다 :)

##### Reference
- https://github.com/woowacourse/service-apply/blob/master/.github/pull_request_template.md#rca-%EB%A3%B0

2023-03-27 15:00 UTC, alex-gibeom commented on src/main/java/woowaapplication/pair/game/wordle/WordleGame.java
> +        return WordleBlock.WRONG;
r: 개발 완료하고나서 주석 지우는 것을 깜빡한 것 같네요 ㅎㅎ!

2023-03-27 15:00 UTC, alex-gibeom commented on src/main/java/woowaapplication/pair/game/wordle/WordleGame.java
> +            .mapToObj(c -> (char)c)
a: 요기도 stream 진행 시 변수명을 좀 더 직관적으로 표현해주면 좋을 것 같습니다 :)

2023-03-27 15:00 UTC, alex-gibeom commented on src/main/java/woowaapplication/pair/game/wordle/WordleGame.java
>          WordleBlock[] result = new WordleBlock[5];
c: 5라는 숫자를 멤버 변수로 관리하거나, `List<WordleBlock>`를 사용해도 좋을 것 같다는 생각이 드네요 :)

2023-03-27 15:00 UTC, alex-gibeom commented on src/main/java/woowaapplication/pair/game/wordle/WordleGame.java
> +    }
a: 메서드 내 추상화 레벨이 동일한 것이 마음이 너무 편하네요 ㅎㅎ 👍🏻👍🏻

2023-03-28 13:29 UTC, giibeom commented on src/main/java/woowaapplication/pair/game/wordle/WordleGame.java
> +        return result;
resultBlocks가 좀 더 직관적일 것 같네요!! 👍🏻👍🏻

2023-03-28 13:30 UTC, seung-00 commented on src/main/java/woowaapplication/pair/game/wordle/WordleGame.java
> +            .mapToObj(c -> (char)c)
> 

`letter` 정도로 바꿔보려는데 어떠세요?

2023-03-28 13:30 UTC, alex-gibeom commented on src/main/java/woowaapplication/pair/game/wordle/WordleGame.java
>          WordleBlock[] result = new WordleBlock[5];
resultBlocks가 좀 더 직관적일 것 같네요!! 👍🏻👍🏻

2023-03-28 13:30 UTC, alex-gibeom commented on src/main/java/woowaapplication/pair/game/wordle/WordleGame.java
> +        return result;
해당 부분은 메서드 반환을 바로 return 시켜도 좋을 것 같습니다 😊

2023-03-28 13:34 UTC, alex-gibeom commented on src/main/java/woowaapplication/pair/game/wordle/WordleGame.java
> +    private WordleBlock compareLetters(char inputKeywordLetter, char answerKeywordLetter, Set<Character> inputKeywordLetters) {
좋은 생각이신거 같습니다!! 👍🏻👍🏻
상위 메서드인 `compareKeywords()`에서 "keywords"라는 명칭을 가지고 있어서 내부 메서드인 `compareLetters`에서는 keyword를 생략해주어도 의미가 통할 것 같네요 :)

2023-03-28 13:34 UTC, seung-00 commented on src/main/java/woowaapplication/pair/game/wordle/WordleGame.java
>          WordleBlock[] result = new WordleBlock[5];
> c: 5라는 숫자를 멤버 변수로 관리하거나, `List<WordleBlock>`를 사용해도 좋을 것 같다는 생각이 드네요 :)

전자 방법으로 수정해보겠습니다 ~ wordleBlock 은 크기가 제한되어 있다는 점이 명세에 있으니 Array 로 관리하면 좋을 것 같아서요~

2023-03-30 10:47 UTC, giibeom approved these changes
LGTM 👍🏻👍🏻

2023-03-30 10:49 UTC, merged